import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "John",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jane",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
    {
      name: "Sam",
      email: "fmba31@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
  ],

  products: [
    {
      name: "BEATS BY DRE HEADSET",
      slug: "beat-by-dre",
      category: "Audio",
      image: "/images/b-headset.png",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      price: 5000,
      brand: "JBL",
      countInStock: "15",
      description: "A nice headset",
    },
    {
      name: "ORIAMO EARBUDS",
      slug: "oriamo-Earbuds",
      category: "Audio",
      image: "/images/Earbuds.jpg",
      isFeatured: true,
      featuredImage: "images/banner2.jpg",
      price: 7000,
      brand: "ORIAMO",
      countInStock: "10",
      description: "A nice headphon",
    },
    {
      name: "32 GIGABITS",
      slug: "SD-32GB-SanDisk",
      category: "storage",
      image: "/images/1.jpg",
      price: 5000,
      brand: "SanDisk",
      countInStock: "5",
      description: "32 Gigabit SanDisk",
    },
    {
      name: "AMAZON POWER BANK",
      slug: "amazon-power-bank",
      category: "Power",
      image: "/images/powerbank.jpg",
      price: 15000,
      brand: "AMAZON",
      countInStock: "15",
      description: "20000 mAh power bank",
    },
    {
      name: "BLUETOOTH EARPIECE",
      slug: "oriamo-bluetooth-earpiece",
      category: "Audio",
      image: "/images/b-earpiece.png",
      price: 2500,
      brand: "ORIAMO",
      countInStock: "15",
      description: "A nice headset",
    },
    {
      name: "WIRELESS KEYBOARD",
      slug: "HP-wireless-keyboard",
      category: "keyboard",
      image: "/images/keyboard.png",
      price: 5000,
      brand: "HP",
      countInStock: "15",
      description: "An wireless keyboard",
    },
    {
      name: "POWER BANK",
      slug: "orima-Power-bank",
      category: "power",
      image: "/images/powerbanko.jpg",
      price: 9500,
      brand: "ORIAMO",
      countInStock: "15",
      description: "An wireless keyboard",
    },
    {
      name: "ORIAMO CHARGER",
      slug: "oriamo-charger",
      category: "power",
      image: "/images/charger.jpg",
      price: 7000,
      brand: "ORIAMO",
      countInStock: "15",
      description: "Oriamo fast charger",
    },
    {
      name: "ORIAMO SPEAKER",
      slug: "oriamo-Speakers",
      category: "Audio",
      image: "/images/o-speaker.jpg",
      price: 10000,
      brand: "ORIAMO",
      countInStock: "18",
      description: "Bluetooth Oriamo speakers",
    },
  ],
};

export default data;
